#define   ROM_CONFIRM            0x0
#define   ROM_LAST_CH             0x8
#define   UNIT_CUR            0x9
#define   E_AUTO_RUN        0xA
#define   ROM_SENSOR_START   0x10
#define   ROM_CH_START       0x100
#define   ROM_SENSOR_LENGTH 12
#define   ROM_CHANNEL_LENGTH 16

#define   ROM_CAL_RATE_START     0x70
/*
#define   CHECKSUM            0xF
#define  S0_NAME_0           0x10
#define  S0_NAME_1           0x11
#define  S0_NAME_2           0x12
#define  S0_NAME_3           0x13
#define  S0_P_UNIT            0x14
#define S0_PRS_MINH           0x15
#define S0_PRS_MINL           0x16
#define S0_PRS_MAXH           0x17
#define S0_PRS_MAXL           0x18
#define  S1_NAME_0           0x1A
#define  S1_NAME_1           0x1B
#define  S1_NAME_2           0x1C
#define  S1_NAME_3           0x1D
#define  S1_P_UNIT            0x1E
#define S1_PRS_MINH           0x1F
#define S1_PRS_MINL           0x20
#define S1_PRS_MAXH           0x21
#define S1_PRS_MAXL           0x22
#define  S2_NAME_0           0x24
#define  S2_NAME_1           0x25
#define  S2_NAME_2           0x26
#define  S2_NAME_3           0x27
#define  S2_P_UNIT            0x28
#define S2_PRS_MINH           0x29
#define S2_PRS_MINL           0x2A
#define S2_PRS_MAXH           0x2B
#define S2_PRS_MAXL           0x2C
#define  S3_NAME_0           0x2E
#define  S3_NAME_1           0x2F
#define  S3_NAME_2           0x30
#define  S3_NAME_3           0x31
#define  S3_P_UNIT            0x32
#define S3_PRS_MINH           0x33
#define S3_PRS_MINL           0x34
#define S3_PRS_MAXH           0x35
#define S3_PRS_MAXL           0x36
#define   CH0_IN_CH           0x50
#define   CH0_SNUM            0x51
#define  CH0_PTYPE            0x52
#define   CH0_UNIT            0x53
#define CH0_TRG_TYPE          0x54
#define CH0_OFFSET_H          0x55
#define CH0_OFFSET_L          0x56
#define CH0_TRGON_H           0x57
#define CH0_TRGON_L           0x58
#define CH0_TRGOFF_H          0x59
#define CH0_TRGOFF_L          0x5A
#define  CH0_HYS_H            0x5B
#define  CH0_HYS_L            0x5C
#define  CH0_DELAY            0x5D
#define CH0_SW_TYPE           0x5E
#define  CH0_CHKSUM           0x5F
#define   CH1_IN_CH           0x60
#define   CH1_SNUM            0x61
#define  CH1_PTYPE            0x62
#define   CH1_UNIT            0x63
#define CH1_TRG_TYPE          0x64
#define CH1_OFFSET_H          0x65
#define CH1_OFFSET_L          0x66
#define CH1_TRGON_H           0x67
#define CH1_TRGON_L           0x68
#define CH1_TRGOFF_H          0x69
#define CH1_TRGOFF_L          0x6A
#define  CH1_HYS_H            0x6B
#define  CH1_HYS_L            0x6C
#define  CH1_DELAY            0x6D
#define CH1_SW_TYPE           0x6E
#define  CH1_CHKSUM           0x6F
#define   CH2_IN_CH           0x70
#define   CH2_SNUM            0x71
#define  CH2_PTYPE            0x72
#define   CH2_UNIT            0x73
#define CH2_TRG_TYPE          0x74
#define CH2_OFFSET_H          0x75
#define CH2_OFFSET_L          0x76
#define CH2_TRGON_H           0x77
#define CH2_TRGON_L           0x78
#define CH2_TRGOFF_H          0x79
#define CH2_TRGOFF_L          0x7A
#define  CH2_HYS_H            0x7B
#define  CH2_HYS_L            0x7C
#define  CH2_DELAY            0x7D
#define CH2_SW_TYPE           0x7E
#define  CH2_CHKSUM           0x7F
#define   CH3_IN_CH           0x80
#define   CH3_SNUM            0x81
#define  CH3_PTYPE            0x82
#define   CH3_UNIT            0x83
#define CH3_TRG_TYPE          0x84
#define CH3_OFFSET_H          0x85
#define CH3_OFFSET_L          0x86
#define CH3_TRGON_H           0x87
#define CH3_TRGON_L           0x88
#define CH3_TRGOFF_H          0x89
#define CH3_TRGOFF_L          0x8A
#define  CH3_HYS_H            0x8B
#define  CH3_HYS_L            0x8C
#define  CH3_DELAY            0x8D
#define CH3_SW_TYPE           0x8E
#define  CH3_CHKSUM           0x8F
#define   CH4_IN_CH           0x90
#define   CH4_SNUM            0x91
#define  CH4_PTYPE            0x92
#define   CH4_UNIT            0x93
#define CH4_TRG_TYPE          0x94
#define CH4_OFFSET_H          0x95
#define CH4_OFFSET_L          0x96
#define CH4_TRGON_H           0x97
#define CH4_TRGON_L           0x98
#define CH4_TRGOFF_H          0x99
#define CH4_TRGOFF_L          0x9A
#define  CH4_HYS_H            0x9B
#define  CH4_HYS_L            0x9C
#define  CH4_DELAY            0x9D
#define CH4_SW_TYPE           0x9E
#define  CH4_CHKSUM           0x9F
#define   CH5_IN_CH           0xA0
#define   CH5_SNUM            0xA1
#define  CH5_PTYPE            0xA2
#define   CH5_UNIT            0xA3
#define CH5_TRG_TYPE          0xA4
#define CH5_OFFSET_H          0xA5
#define CH5_OFFSET_L          0xA6
#define CH5_TRGON_H           0xA7
#define CH5_TRGON_L           0xA8
#define CH5_TRGOFF_H          0xA9
#define CH5_TRGOFF_L          0xAA
#define  CH5_HYS_H            0xAB
#define  CH5_HYS_L            0xAC
#define  CH5_DELAY            0xAD
#define CH5_SW_TYPE           0xAE
#define  CH5_CHKSUM           0xAF
#define   CH6_IN_CH           0xB0
#define   CH6_SNUM            0xB1
#define  CH6_PTYPE            0xB2
#define   CH6_UNIT            0xB3
#define CH6_TRG_TYPE          0xB4
#define CH6_OFFSET_H          0xB5
#define CH6_OFFSET_L          0xB6
#define CH6_TRGON_H           0xB7
#define CH6_TRGON_L           0xB8
#define CH6_TRGOFF_H          0xB9
#define CH6_TRGOFF_L          0xBA
#define  CH6_HYS_H            0xBB
#define  CH6_HYS_L            0xBC
#define  CH6_DELAY            0xBD
#define CH6_SW_TYPE           0xBE
#define  CH6_CHKSUM           0xBF
#define   CH7_IN_CH           0xC0
#define   CH7_SNUM            0xC1
#define  CH7_PTYPE            0xC2
#define   CH7_UNIT            0xC3
#define CH7_TRG_TYPE          0xC4
#define CH7_OFFSET_H          0xC5
#define CH7_OFFSET_L          0xC6
#define CH7_TRGON_H           0xC7
#define CH7_TRGON_L           0xC8
#define CH7_TRGOFF_H          0xC9
#define CH7_TRGOFF_L          0xCA
#define  CH7_HYS_H            0xCB
#define  CH7_HYS_L            0xCC
#define  CH7_DELAY            0xCD
#define CH7_SW_TYPE           0xCE
#define  CH7_CHKSUM           0xCF
*/
